spring:
  cloud:
    gateway:
      routes:
        - id: shopping-cart-route
          uri: lb://shopping-cart
          predicates:
            - Path=/shopping-cart/**
          filters:
            - PrefixPath=/api/v1

        - id: shopping-store-route
          uri: lb://shopping-store
          predicates:
            - Path=/shopping-store/**
          filters:
            - PrefixPath=/api/v1
            - name: Retry
              args:
                retries: 3
                statuses:
                  - INTERNAL_SERVER_ERROR
                exceptions:
                  - ru.practicum.interaction.exception.ProductNotFoundException
                methods: GET

        - id: warehouse-route
          uri: lb://warehouse
          predicates:
            - Path=/warehouse/**
          filters:
            - PrefixPath=/api/v1

management:
  endpoints:
    web:
      exposure:
        include: health,info,gateway
  endpoint:
    gateway:
      enabled: true

logging:
  level:
    ru.practicum.infra.gateway: DEBUG
    org.springframework.cloud.gateway: DEBUG