spring:
  kafka:
    bootstrap-servers: localhost:9092

analyzer:
  kafka:
    bootstrap-servers: ${spring.kafka.bootstrap-servers:localhost:9092}
    snapshots-topic: telemetry.snapshots.v1
    hubs-topic: telemetry.hubs.v1
    poll-timeout-ms: 1000
    snapshot-consumer:
      key.deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value.deserializer: ru.practicum.telemetry.analyzer.serialization.SensorsSnapshotDeserializer
      group.id: analyzer-snapshot-group
      enable.auto.commit: false
      auto.offset.reset: earliest
    hub-consumer:
      key.deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value.deserializer: ru.practicum.telemetry.analyzer.serialization.HubEventDeserializer
      group.id: analyzer-hub-group
      enable.auto.commit: false
      auto.offset.reset: earliest

grpc:
  client:
    hub-router:
      address: 'static://localhost:59090'
      enableKeepAlive: true
      keepAliveWithoutCalls: true
      negotiationType: plaintext

logging:
  level:
    ru.practicum.telemetry.analyzer: DEBUG
    org.apache.kafka: WARN
    org.hibernate.SQL: WARN